QSHOP/urls.py
from django.contrib import admin
from django.urls import path,include

from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('goods/',include('goods.urls',namespace='goods')),
    path('manager/',include('manager.urls',namespace='manager')),
    path('user/',include('user.urls',namespace='user')),
    #用于重定向
    path('',RedirectView.as_view(url="/goods/index")),

]

goods/urls.py
from django.urls import path
from goods import views

urlpatterns = [
    path('index/',views.Index.as_view(),name="index"),
    path('list/',views.List.as_view(),name="list"),
    path('goods/',views.goods.as_view(),name="goods"),
    path('check_count/',views.check_count,name="check_count"),
    path('search/',views.search,name="search"),
    path('demo/vue/api/',views.DemoVueApi,name="DemoVueApi"),
    path('demo/',views.demo,name="demo"),
]
app_name='goods'

user/urls.py
from django.urls import path,re_path
from user import views

from django.views.decorators.csrf import csrf_exempt
from QSHOP.common import user_login_valid
urlpatterns = [
    path('register/',views.Register.as_view(),name='register'),
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('carts/',views.carts.as_view(),name ="carts"),
    path('user_info/',views.User_info.as_view(),name ="user_info"),
    path('user_order/',views.User_order.as_view(),name ="user_order"),
    path('user_site/',views.User_site.as_view(),name ="user_site"),
    path('set_address/',views.set_address,name ="set_address"),
    path('carts_check_count/',views.carts_check_count,name ="carts_check_count"),
    path('place_order/',views.place_order,name ="place_order"),
    path('create_order/',views.create_order,name ="create_order"),
    path('select_carts_count/',views.select_carts_count,name ="select_carts_count"),
    path('pay_order/<int:order_id>',views.pay_order,name ="pay_order"),
    path('test_time/',views.test_time,name ="test_time"),
    path('return_url/',views.return_url,name ="return_url"),
    path('receive_goods/<int:orderinfo_id>',views.receive_goods,name ="receive_goods"),
    path('comment/<int:orderinfo_id>',views.comment,name ="comment"),
    path('reminder/<int:orderinfo_id>',views.reminder,name ="reminder"),

]
app_name='user'

urlpatterns += [
    # 使用装饰器装饰类
    path('Demo/', user_login_valid(views.Demo.as_view()), name="Demo"),
    # re_path('demo/(\d+)/(?P<id2>\d+)',views.demo,name='demo'),
]

goods/models.py
from django.db import models
from manager.models import  Manager

class Type(models.Model):
    class Meta:
        verbose_name = '商品类别'
        verbose_name_plural = '商品类别'
    type_name = models.CharField(max_length=50,verbose_name='类别名称')
    date = models.DateTimeField(auto_now_add=True,verbose_name='添加时间')
    def __str__(self):
        return  self.type_name

class Goods(models.Model):
    class Meta:
        verbose_name = '商品'
        verbose_name_plural = '商品'

    goods_name = models.TextField(verbose_name='商品名称')
    goods_oprice = models.FloatField(verbose_name='现价')
    goods_xprice = models.FloatField(verbose_name='原价')
    goods_count = models.IntegerField(default=0,verbose_name='商品数量')
    goods_production = models.DateTimeField(auto_now=True,verbose_name='生产日期')
    safe_date = models.CharField(max_length=10,verbose_name='保质期')
    goods_method = models.CharField(max_length=100,verbose_name='存储方法')
    goods_description = models.TextField(verbose_name='商品简介')
    goods_pic = models.ImageField(upload_to='media/goods/image',verbose_name='商品图片')
    goods_address = models.CharField(max_length=50,verbose_name='配送地址')
    goods_info = models.TextField(verbose_name='商品详情')
    manager = models.ForeignKey(Manager,on_delete=models.CASCADE,verbose_name='商家')
    type = models.ForeignKey(Type,on_delete=models.CASCADE,verbose_name='类别')
    status = models.BooleanField(default=1,verbose_name='商品状态')   #0代表下架，1代表上架

    def __str__(self):
        return self.goods_name   #外键关联时直接通过外键显示商品名称

goods/views.py
from django.shortcuts import render
from django.views import View
from goods.models import Type, Goods
from django.http import Http404, JsonResponse, HttpResponse, HttpResponseRedirect
from QSHOP.common import set_page
from django.db.models import Q
from user.models import Hobby
from django.views.decorators.csrf import csrf_exempt

# 首页
class Index(View):
    def get(self, request):
        type_list = Type.objects.all()
        goods = {}
        for type in type_list:
            goods[type.id] = Goods.objects.filter(type_id=type.id, status=1, goods_count__gt=0)[:4]
        print(goods)
        return render(request, 'goods_common/index.html', {"goods": goods})


# 商品列表
class List(View):
    def __init__(self):
        super(List, self).__init__()
        self.result = {
            'code': 200,
            'data': [],
            'page_range': [],
            'p': 1,
            'page_next': False,
            'page_previous': False,
        }
        self.message = ""

    def get(self, request):
        t_id = request.GET.get('t_id', 0)
        try:
            t_id = int(t_id)
        except:
            t_id = 0
        goods_name = request.GET.get("name", '')
        self.message = goods_name
        if request.is_ajax():
            if 0 < t_id < 7:
                goods_list = Goods.objects.filter(type_id=t_id, status=1, goods_count__gt=0)
            else:
                goods_list = Goods.objects.filter(status=1, goods_count__gt=0)
            if goods_name:
                goods_list = goods_list.filter(
                    (Q(goods_name__contains=goods_name) | Q(type__type_name__contains=goods_name)), status=1,
                    goods_count__gte=1)
            try:
                page = int(request.GET.get('page', 1))
            except:
                page = 1
            data, page_range = set_page(goods_list, 10, page)
            if data.has_next():
                page_next = data.next_page_number
                self.result['page_next'] = page_next()
            if data.has_previous():
                page_previous = data.previous_page_number
                self.result['page_previous'] = page_previous()
            for goods in data:
                dict1 = {
                    'id': goods.id,
                    'goods_name': goods.goods_name,
                    'goods_pic': goods.goods_pic.url,
                    'goods_oprice': goods.goods_oprice,
                    'goods_xprice': goods.goods_xprice,
                }
                self.result['data'].append(dict1)
            self.result['page_range'] = list(page_range)
            self.result['p'] = page
            print(self.result)
            return JsonResponse(self.result)
        return render(request, 'goods_common/list.html', {"t_id": t_id, "name": self.message})


# 商品搜索
def search(request):
    data = request.GET
    goods_name = data.get("name")
    return HttpResponseRedirect("/goods/list/?name={}".format(goods_name))


# 商品详情
class goods(View):
    def __int__(self):
        super(goods, self).__init__()

    def get(self, request):
        goods_id = request.GET.get('goods_id')
        if goods_id:
            goods = Goods.objects.filter(id=goods_id, status=1, goods_count__gt=0)
            if goods.exists():
                goods = goods[0]
                goods_list = Goods.objects.filter(status=1, goods_count__gt=0, type_id=goods.type_id).exclude(
                    id=goods_id)[:2]
                return render(request, 'goods_common/detail.html', {'goods': goods, 'goods_list': goods_list})
        raise Http404


# 加购之前检测库存
def check_count(request):
    if request.method == "POST":
        data = request.POST
        goods_id = data.get('goods_id')
        count = int(data.get('count'))
        goods = Goods.objects.filter(id=goods_id, status=1, goods_count__gt=0)
        result = {}
        if goods.exists():
            goods = goods[0]
            status = 1
            if count > goods.goods_count:
                count = goods.goods_count
            result['count'] = count
        else:
            status = 0
        result['status'] = status
        return JsonResponse(result)
    return HttpResponse("请求方式有误！")


#vue示例
import json
@csrf_exempt
def DemoVueApi(request):
    if request.method=="POST":
        data = json.loads(request.body.decode("utf-8"))
        print(data.get("firstName"))
        r = {"data":1}
        return JsonResponse(r)
    return render(request,'demo_vue.html')



# 测试 process_exception
def demo(request):
    Goods.objects.get(id=1000000000000)
    return HttpResponse("1111")

goods/templates/goods_common/detail.html
{% extends 'base/user_base.html' %}
{% load static %}

{% block title %}
    <title>商品详情</title>
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
    {% include 'base/user_header.html' %}

    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/static/{{ goods.goods_pic }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.goods_name }}</h3>
			<p>{{ goods.goods_description }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.goods_oprice }}</em></span>
				<del class="show_unit">原价：{{ goods.goods_xprice }}</del>
			</div>
            <form action="{% url 'user:carts' %}" method="post" id="add_car">
                {% csrf_token %}
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
                    <input type="hidden" value="{{ goods.id }}" id="goods_id" name="goods_id">
					<input type="text" class="num_show fl"  value="1" id="show_count" name="count" onblur="change_count('change')">
					<a href="javascript:;" class="add fr" onclick="change_count('add')">+</a>
					<a href="javascript:;" class="minus fr" onclick="change_count('delete')">-</a>
				</div>
			</div>
			<div class="total">总价：<em id="total">{{ goods.goods_oprice }}</em>元</div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn" onclick="place_order()">立即购买</a>
				<button type="submit" class="add_cart" id="add_cart" style="height: 40px;">加入购物车</button>
			</div>
            </form>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for foo in goods_list %}
                    <li>
						<a href="{% url 'goods:goods' %}?goods_id={{ foo.id }}"><img src="/static/{{ foo.goods_pic }}"></a>
						<h4><a href="{% url 'goods:goods' %}?goods_id={{ foo.id }}">{{ foo.goods_name }}</a></h4>
						<div class="prize">￥{{ foo.goods_oprice }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods_info | safe}} </dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}

{% block script %}
    <div class="add_jump"></div>

	<script type="text/javascript" src="/static/user/js/jquery-1.11.0.js"></script>
	<script type="text/javascript">
        console.log($('#add_cart').offset().top);

		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});
			});
		});

        change_count =function (type) {
            var count = parseInt($('#show_count').val());
            if(count<=0){
                $('#show_count').val(1)
            }
            else {
                if(type=="add"){
                count+=1;
                }else{
                    if(type=="delete"){
                         if(count>1){count-=1}
                    }
                }
                f(count)
            }
        };
        $('#add_car').submit(function () {
            var count = parseInt($('#show_count').val());
            f(count)
        });
        function f(count) {
            var goods_id = $('#goods_id').val();
            var csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]').val();
            var price = {{ goods.goods_oprice }}
            $.ajax({
                url:"{% url 'goods:check_count' %}",
                data:{goods_id:goods_id,csrfmiddlewaretoken:csrfmiddlewaretoken,count:count},
                dataType:"json",
                type:"post",
                success:function (data) {
                if(data.status == 1){
                    $('#show_count').val(data.count);
                    $('#total').html(price*data.count)
                    }
                    else{
                        window.alert("商品已下架，请选择其他商品。")
                        window.location.href="{% url 'goods:list' %}"
                        }
                }
            })
        }

        function place_order() {
            var add_car = window.document.getElementById("add_car");
            console.log(add_car.action,1111);
            add_car.action = "/user/place_order/";
            console.log(add_car.action,222);
            add_car.submit();
        }
	</script>
{% endblock %}

goods/templates/goods_common/index.html
{% extends 'base/user_base.html' %}
{% load static %}
{% load manager_extras %}
{% load goods_extras %}

{% block title %}
    <title>首页</title>
{% endblock %}

{% block style %}
    <script type="text/javascript" src="/static/user/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/user/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/user/js/slide.js"></script>
{% endblock %}

{% block content %}
    {% include 'base/user_header.html' %}

    <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/user/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/user/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/user/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/user/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/user/images/adv01.jpg"></a>
			<a href="#"><img src="/static/user/images/adv02.jpg"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">新鲜水果</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="{% url 'goods:search' %}?name=鲜芒">鲜芒</a>
				<a href="{% url 'goods:search' %}?name=加州提子">加州提子</a>
				<a href="{% url 'goods:search' %}?name=鲜芒">亚马逊牛油果</a>
			</div>
			<a href="/goods/list?t_id=1" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/user/images/banner01.jpg"></div>
			<ul class="goods_list fl">
                {% for goods in goods.1|set_goods_number %}
				<li>
					<h4><a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}">{{ goods.goods_name | set_goods_name }}</a></h4>
					<a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}"><img src="/static/{{ goods.goods_pic }}"></a>
					<div class="prize">现价：¥ {{ goods.goods_oprice }}</div>
					<del style="">原价：¥ {{ goods.goods_xprice }}</del>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">海鲜水产</h3>
			<div class="subtitle fl">
				<span>|</span>
{#				<a href="#">河虾</a>#}
{#				<a href="#">扇贝</a>#}
                <a href="{% url 'goods:search' %}?name=河虾">河虾</a>
				<a href="{% url 'goods:search' %}?name=扇贝">扇贝</a>
{#				<a href="{% url 'goods:search' %}?name=鲜芒">亚马逊牛油果</a>#}
			</div>
			<a href="/goods/list?t_id=2" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/user/images/banner02.jpg"></div>
			<ul class="goods_list fl">
				 {% for goods in goods.2|set_goods_number %}
				<li>
					<h4><a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}">{{ goods.goods_name | set_goods_name}}</a></h4>
					<a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}"><img src="/static/{{ goods.goods_pic }}"></a>
					<div class="prize">现价：¥ {{ goods.goods_oprice }}</div>
					<del style="">原价：¥ {{ goods.goods_xprice }}</del>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">猪牛羊肉</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="{% url 'goods:search' %}?name=鲜芒">鲜芒</a>
				<a href="{% url 'goods:search' %}?name=加州提子">加州提子</a>
				<a href="{% url 'goods:search' %}?name=鲜芒">亚马逊牛油果</a>
			</div>
			<a href="/goods/list?t_id=3" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/user/images/banner03.jpg"></div>
			<ul class="goods_list fl">
			 {% for goods in goods.3|set_goods_number %}
				<li>
					<h4><a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}">{{ goods.goods_name | set_goods_name}}</a></h4>
					<a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}"><img src="/static/{{ goods.goods_pic }}"></a>
					<div class="prize">现价：¥ {{ goods.goods_oprice }}</div>
					<del style="">原价：¥ {{ goods.goods_xprice }}</del>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">禽类蛋品</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="{% url 'goods:search' %}?name=鲜芒">鲜芒</a>
				<a href="{% url 'goods:search' %}?name=加州提子">加州提子</a>
				<a href="{% url 'goods:search' %}?name=鲜芒">亚马逊牛油果</a>
			</div>
			<a href="/goods/list?t_id=4" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/user/images/banner04.jpg"></div>
			<ul class="goods_list fl">
				 {% for goods in goods.4|set_goods_number %}
				<li>
					<h4><a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}">{{ goods.goods_name | set_goods_name }}</a></h4>
					<a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}"><img src="/static/{{ goods.goods_pic }}"></a>
					<div class="prize">现价：¥ {{ goods.goods_oprice }}</div>
					<del style="">原价：¥ {{ goods.goods_xprice }}</del>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">新鲜蔬菜</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="{% url 'goods:search' %}?name=鲜芒">鲜芒</a>
				<a href="{% url 'goods:search' %}?name=加州提子">加州提子</a>
				<a href="{% url 'goods:search' %}?name=鲜芒">亚马逊牛油果</a>
			</div>
			<a href="/goods/list?t_id=5" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/user/images/banner05.jpg"></div>
			<ul class="goods_list fl">
			 {% for goods in goods.5|set_goods_number %}
				<li>
					<h4><a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}">{{ goods.goods_name |set_goods_name}}</a></h4>
					<a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}"><img src="/static/{{ goods.goods_pic }}"></a>
					<div class="prize">现价：¥ {{ goods.goods_oprice }}</div>
					<del style="">原价：¥ {{ goods.goods_xprice }}</del>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">速冻食品</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="{% url 'goods:search' %}?name=鲜芒">鲜芒</a>
				<a href="{% url 'goods:search' %}?name=加州提子">加州提子</a>
				<a href="{% url 'goods:search' %}?name=鲜芒">亚马逊牛油果</a>
			</div>
			<a href="/goods/list?t_id=6" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/user/images/banner06.jpg"></div>
			<ul class="goods_list fl">
			 {% for goods in goods.6|set_goods_number %}
				<li>
					<h4><a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}">{{ goods.goods_name |set_goods_name}}</a></h4>
					<a href="{% url 'goods:goods' %}?goods_id={{ goods.id }}"><img src="/static/{{ goods.goods_pic }}"></a>
					<div class="prize">现价：¥ {{ goods.goods_oprice }}</div>
					<del style="">原价：¥ {{ goods.goods_xprice }}</del>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endblock %}

{% block script %}
{#    <script type="text/javascript" src="/static/user/js/slideshow.js"></script>#}
	<script type="text/javascript">
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = '/goods/list';
		}
	</script>
{% endblock %}

goods/templates/goods_common/list.html
{% extends 'base/user_base.html' %}
{% load static %}

{% block title %}
    <title>商品列表</title>
{% endblock %}

{% block style %}
    <script src="/static/goods/js/vue.js"></script>
    <script src="/static/goods/js/vue-resource.js"></script>
{% endblock %}

{% block content %}
    {% include 'base/user_header.html' %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix" id="content">
    {% verbatim myblock%}
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
				<li v-for="goods in new_goods_list">
					<a v-bind:href="'/goods/goods?goods_id='+goods.id"><img v-bind:src="'/static/'+goods.goods_pic"></a>
					<h4><a v-bind:href="'/goods/goods?goods_id='+goods.id">{{ goods.goods_name }}</a></h4>
					<div class="prize">￥{{ goods.goods_oprice }}</div>
				</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				<li v-for="goods in goods_list">
					<a v-bind:href="'/goods/goods?goods_id='+goods.id"><img v-bind:src="'/static/'+goods.goods_pic"></a>
					<h4><a v-bind:href="'/goods/goods?goods_id='+goods.id">{{ goods.goods_name }}</a></h4>
					<div class="operate">
						<span class="prize">现价:￥{{ goods.goods_oprice }}</span>
						<del class="unit">原价:￥{{ goods.goods_xprice }}</del>
						<a v-bind:href="'/user/carts?goods_id='+goods.id" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			</ul>

			<div class="pagenation">

				<a v-if="page_previous" @click="click(page_previous)" href="javascript:;">&lt;上一页</a>
                <span v-for="page in page_range">
                    <a @click="click(page)" class="active" v-if="p == page" href="javascript:;">{{ page }}</a>
                    <a @click="click(page)" v-else href="javascript:;">{{ page }}</a>
                </span>
				<a v-if="page_next" @click="click(page_next)" href="javascript:;">下一页&gt;</a>
			</div>
		</div>
	{% endverbatim myblock%}
	</div>

{% endblock %}

{% block script %}
    <script>
    {#fn=#}
    var t_id = {{ t_id }};
    var name = $("input[name='name']").val();
    Vue.use(VueResource);
    var vue = new Vue({
        el:"#content",
        data:{
            goods_list:"",
            page_range:"",
            p:"",
            page_next:"",
            page_previous:"",
            new_goods_list:[]
        },
        methods:{
            click:function (page) {
                url='{% url "goods:list" %}?t_id='+t_id+'&page='+page+"&name="+name;
                console.log(url);
                this.$http.get(url).then(
                    //相当于ajax中的success
                    function (data) {
                        console.log(data['data']);
                        this.goods_list = data['data']['data'];
                        this.new_goods_list = data['data']['data'].slice(0,2);
                        this.page_range = data['data']['page_range'];
                        this.p =  data['data']['p'];
                        this.page_next =  data['data']['page_next'];
                        this.page_previous =  data['data']['page_previous'];
                    },
                    function (error) {
                        console.log(error)
                    }
                )
            }
        },
        created(){this.click(1)}
    });

    </script>
{% endblock %}