QSHOP/urls.py
from django.contrib import admin
from django.urls import path,include

from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('goods/',include('goods.urls',namespace='goods')),
    path('manager/',include('manager.urls',namespace='manager')),
    path('user/',include('user.urls',namespace='user')),
    #用于重定向
    path('',RedirectView.as_view(url="/goods/index")),

]

goods/urls.py
from django.urls import path
from goods import views

urlpatterns = [
    path('index/',views.Index.as_view(),name="index"),
    path('list/',views.List.as_view(),name="list"),
    path('goods/',views.goods.as_view(),name="goods"),
    path('check_count/',views.check_count,name="check_count"),
    path('search/',views.search,name="search"),
    path('demo/vue/api/',views.DemoVueApi,name="DemoVueApi"),
    path('demo/',views.demo,name="demo"),
]
app_name='goods'

user/urls.py
from django.urls import path,re_path
from user import views

from django.views.decorators.csrf import csrf_exempt
from QSHOP.common import user_login_valid
urlpatterns = [
    path('register/',views.Register.as_view(),name='register'),
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('carts/',views.carts.as_view(),name ="carts"),
    path('user_info/',views.User_info.as_view(),name ="user_info"),
    path('user_order/',views.User_order.as_view(),name ="user_order"),
    path('user_site/',views.User_site.as_view(),name ="user_site"),
    path('set_address/',views.set_address,name ="set_address"),
    path('carts_check_count/',views.carts_check_count,name ="carts_check_count"),
    path('place_order/',views.place_order,name ="place_order"),
    path('create_order/',views.create_order,name ="create_order"),
    path('select_carts_count/',views.select_carts_count,name ="select_carts_count"),
    path('pay_order/<int:order_id>',views.pay_order,name ="pay_order"),
    path('test_time/',views.test_time,name ="test_time"),
    path('return_url/',views.return_url,name ="return_url"),
    path('receive_goods/<int:orderinfo_id>',views.receive_goods,name ="receive_goods"),
    path('comment/<int:orderinfo_id>',views.comment,name ="comment"),
    path('reminder/<int:orderinfo_id>',views.reminder,name ="reminder"),

]
app_name='user'

urlpatterns += [
    # 使用装饰器装饰类
    path('Demo/', user_login_valid(views.Demo.as_view()), name="Demo"),
    # re_path('demo/(\d+)/(?P<id2>\d+)',views.demo,name='demo'),
]

user/models.py
from django.db import models
from goods.models import Goods
from manager.models import Manager



#卖家用户表
class User(models.Model):
    class Meta:
        verbose_name = "买家用户"
        verbose_name_plural = "买家用户"

    user_name = models.CharField(max_length=20)
    email = models.EmailField('买家邮箱')
    password = models.CharField(max_length=32,verbose_name='买家密码')
    image = models.ImageField(upload_to='media/user/image',default='media/user/image/user_default.jpg')
    is_login = models.BooleanField(default=0)

    def __str__(self):
        return self.user_name


#购物车表
class Carts(models.Model):
    class Meta:
        verbose_name = "购物车"
        verbose_name_plural = "购物车"
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='买家')
    goods = models.ForeignKey(Goods,on_delete=models.CASCADE,verbose_name="商品")
    count = models.IntegerField('数量')


#收货地址表
class Address(models.Model):
    class Meta:
        verbose_name = "收获地址"
        verbose_name_plural = "收获地址"
    username = models.CharField(max_length=25,verbose_name="收货人姓名")
    userphone = models.CharField(max_length=20,verbose_name="收货人电话")
    address = models.CharField(max_length=255, verbose_name="详细地址")
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="买家")
    isdefault = models.BooleanField(default=0,verbose_name="是否默认地址")        #0否，1是
    createtime = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")


#订单总表
class Order(models.Model):
    class Meta:
        verbose_name = "订单"
        verbose_name_plural = "订单"
    total_code = models.CharField(max_length=17,unique=True,verbose_name="订单总编号")
    user = models.ForeignKey(User,verbose_name="买家",on_delete=models.DO_NOTHING)
    add_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")
    contacts = models.CharField(max_length=30, verbose_name="收货人")
    address = models.CharField(max_length=255,verbose_name="收货地址")
    phone = models.CharField(max_length=20,verbose_name="收货人电话")
    pay_status = models.BooleanField(default=0,verbose_name="支付状态")  #默认为0，未支付
    pay_time = models.DateTimeField(null=True,verbose_name="支付时间")
    total_money = models.FloatField(verbose_name="价格")
    def __str__(self):
        return self.total_code


#订单详情表
class Order_info(models.Model):
    class Meta:
        verbose_name = "订单详情"
        verbose_name_plural = "订单详情"
    order_code = models.CharField(max_length=32,verbose_name="订单详细编号")
    order = models.ForeignKey(Order,verbose_name="订单", on_delete=models.DO_NOTHING)
    goods = models.ForeignKey(Goods,verbose_name="商品", on_delete=models.DO_NOTHING)
    number = models.IntegerField(default=1, verbose_name="数量")
    money = models.FloatField(verbose_name="价格")
    send_status = models.BooleanField(default=0,verbose_name="发货状态")
    send_time = models.DateTimeField(null=True,verbose_name="发货时间")
    receive_status = models.BooleanField(default=0, verbose_name="收货状态")
    receive_time = models.DateTimeField(null=True, verbose_name="收货时间")
    comment_status = models.BooleanField(default=0, verbose_name="评价状态")
    manager = models.ForeignKey(Manager, verbose_name="商家", on_delete=models.DO_NOTHING)


#用户爱好表
class Hobby(models.Model):
    class Meta:
        verbose_name = "买家爱好"
        verbose_name_plural = "买家爱好"
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='买家')
    goods = models.ForeignKey(Goods,on_delete=models.CASCADE,verbose_name="商品")


#用户评价表
class Comment(models.Model):
    class Meta:
        verbose_name = "商品评价"
        verbose_name_plural = "商品评价"
    goods_score = models.FloatField(verbose_name="商品评分")
    service_score = models.FloatField(verbose_name="客服评分")
    logistics_score = models.FloatField(verbose_name="物流评分")
    content = models.TextField(verbose_name="评价内容")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="评价时间")
    shop_reply = models.TextField(verbose_name="商家回复")
    reply_time = models.DateTimeField(null=True, verbose_name="商家回复时间")
    user = models.ForeignKey(User,verbose_name="买家用户",on_delete=models.CASCADE)
    orderinfo = models.ForeignKey(Order_info,on_delete=models.CASCADE,verbose_name="订单详情")
    is_anonymous = models.BooleanField(verbose_name="是否匿名评价")

user/views.py
from django.shortcuts import render, redirect,render_to_response
from django.views import View
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect, QueryDict,FileResponse
from user.models import User, Carts, Order, Order_info,Address,Comment
from QSHOP.common import set_password
from QSHOP.common import user_login_valid
from goods.models import Goods
from django.views.decorators.csrf import csrf_exempt
import time
from QSHOP.common import set_page,Pay,send_manager_email
from django.http import Http404
from django.utils import timezone



# 注册
class Register(View):
    def get(self, request):
        if request.is_ajax():
            user_name = request.GET.get('user_name')
            result = {'flag': 1}
            user = User.objects.filter(user_name=user_name)
            if user.exists():
                result['flag'] = 0
            return JsonResponse(result)
        return render(request, 'user_common/register.html')

    def post(self, request):
        data = request.POST
        user_name = data.get('user_name')
        password = data.get('password')
        email = data.get('email')
        pwd = set_password(set_password(set_password(password)))
        u = User()
        u.user_name = user_name
        u.password = pwd
        u.email = email
        u.save()
        return redirect('user:login')


# 登录
class Login(View):

    def __init__(self):
        super(Login, self).__init__()
        self.message = ''

    def get(self, request):
        next = request.GET.get("next", "")
        refer = request.META.get("HTTP_REFERER")
        print(refer, 11111111)
        print(next)
        return render(request, 'user_common/login.html', {'message': self.message, 'next': next})

    def post(self, request):
        data = request.POST
        user_name = data.get('user_name')
        passwrod = data.get('password')
        pwd = set_password(set_password(set_password(passwrod)))
        u = User.objects.filter(user_name=user_name, password=pwd)
        if u.exists():
            request.session['user_name'] = user_name
            request.session['user_id'] = u[0].id
            next = data.get('next')
            if next:
                response = HttpResponseRedirect(next)
            else:
                response = HttpResponseRedirect('/goods/index')
            response.set_cookie('user_name', user_name)
            return response
        else:
            self.message = "用户名或密码有误！"
            return self.get(request)


# 退出
class Logout(View):
    def __int__(self):
        super(Logout, self).__init__()

    def get(self, request):
        response = redirect('user:login')
        try:
            del request.session['user_name']
            del request.session['user_id']
            response.delete_cookie('user_name')
        except:
            pass
        return response


# 购物车
class carts(View):
    def __init__(self):
        super(carts, self).__init__()
        self.result = {}

    def get(self, request):
        user_id = request.session.get('user_id')
        if not user_id:
            return HttpResponseRedirect('/user/login?next=/user/carts')
        goods_id = request.GET.get("goods_id",0)
        if goods_id:
            return self.add_car(request,'get')
        carts_list = Carts.objects.filter(user_id=user_id, goods__status=1, goods__goods_count__gt=0)
        return render(request, 'user_common/cart.html', {"carts_list": carts_list})

    def post(self, request):
        print(request.POST.get('type'))
        if request.POST.get('type') == "delete":
            return self.delete(request)
        return self.add_car(request,'post')

    def add_car(self, request,type):
        if type == "post":
            data = request.POST
            count = int(data.get('count'))
        else:
            data = request.GET
            count = 1
        user_id = request.session.get('user_id')
        visit_url = request.resolver_match.url_name
        print(visit_url, 1111111)
        if not user_id:
            return HttpResponseRedirect('/user/login')
        goods_id = data.get('goods_id')
        goods = Goods.objects.filter(id=goods_id, status=1, goods_count__gt=0)
        if goods.exists():
            goods = goods[0]
            Cart = Carts.objects.filter(user_id=user_id, goods_id=goods_id)
            if Cart.exists():
                c = Cart[0]
                if c.count + count <= goods.goods_count:
                    c.count += count
                else:
                    c.count = goods.goods_count
                c.save()
            else:
                c = Carts()
                if goods.goods_count >= count:
                    c.count = count
                else:
                    c.count = goods.goods_count
                c.user_id = user_id
                c.goods_id = goods_id
                c.save()
            return redirect('user:carts')
        return redirect('goods:list')

    def delete(self, request):
        data = request.POST
        carts_id = data.get("carts_id")
        user_id = request.session.get("user_id",None)
        if user_id:
            try:
                Carts.objects.get(id=carts_id,user_id=user_id).delete()
                self.result['status'] = 1   #删除成功
            except:
                self.result['status'] = 0   #删除失败
        else:
            self.result['status'] = 2       #未登录
        return JsonResponse(self.result)


# 购物车中检测库存
def carts_check_count(request):
    if request.method == "POST":
        data = request.POST
        carts_id = data.get('carts_id')
        count = int(data.get('count'))
        print("count", count)
        result = {'status': 1, "count": count}
        car = Carts.objects.filter(id=carts_id)
        if car.exists():
            car = car[0]
            if car.goods.status == 1 and car.goods.goods_count > 0:
                number = car.goods.goods_count
                if count >= number:
                    car.count = number
                    print(car.count, 111)
                    car.save()
                    result['data'] = number
                else:
                    car.count = count
                    car.save()
                    print(car.count, 2222222)
                    result['data'] = car.count
            else:
                result['status'] = 0
                result['data'] = '/user/carts'
        else:
            result['status'] = 0
            result['data'] = '/user/carts'
        return JsonResponse(result)
    return HttpResponse("请求方式有误！")


# 提交订单
@user_login_valid
def place_order(requet):
    if requet.method == "POST":
        user_id = requet.session.get('user_id')
        data = requet.POST
        result = []
        total_money = 0
        goods_id = data.get("goods_id",0)
        if goods_id:
            #直接购买
            count = int(data.get("count"))
            print(count,1111111111)
            goods_list = Goods.objects.filter(id=goods_id,status=1,goods_count__gte=count)
            for i in range(len(goods_list)):
                xiaoji = count * goods_list[i].goods_oprice
                result.append({
                    'number': i + 1,
                    'goods_id': goods_list[i].id,
                    'image': goods_list[i].goods_pic.url,
                    'goods_name': goods_list[i].goods_name,
                    'oprice': goods_list[i].goods_oprice,
                    'xprice': goods_list[i].goods_xprice,
                    'count': count,
                    'xiaoji': xiaoji
                })
                total_money += xiaoji
        else:
            #购物车进行结算
            carts = data.getlist('carts_name')
            car_list = Carts.objects.filter(id__in=carts, user_id=user_id, goods__status=1)

            for i in range(len(car_list)):
                xiaoji = car_list[i].count * car_list[i].goods.goods_oprice
                result.append({
                    'number': i + 1,
                    'id': car_list[i].id,
                    'image': car_list[i].goods.goods_pic.url,
                    'goods_name': car_list[i].goods.goods_name,
                    'oprice': car_list[i].goods.goods_oprice,
                    'xprice': car_list[i].goods.goods_xprice,
                    'count': car_list[i].count,
                    'xiaoji': xiaoji
                })
                total_money += xiaoji
        data = {}
        data['money'] = total_money
        data['result'] = result
        address_list = Address.objects.filter(user_id=user_id)
        return render(requet, 'user_common/place_order.html', {"data": data, "address_list": address_list})
    return HttpResponse("请求方式有误")


# 创建订单
@user_login_valid
def create_order(request):
    if request.method == "POST":
        data = request.POST
        address = data.get("address", 0)

        user_id = request.session.get("user_id")
        a = Address.objects.filter(id=address, user_id=user_id).first()
        if not a:
            return HttpResponse("请选择收货地址！")
        total_money = 0
        goods_id = data.get("goods_id")
        flag = False   #判断是直接购买还是从购物车中购买
        if goods_id:
            count  = int(data.get("count"))
            goods = Goods.objects.filter(id=goods_id,goods_count__gte=count,status=1).first()
            print(count,goods,111111111111111)
            if not goods:
                return HttpResponse("商品信息有误，请重新选择！")
            goods.goods_count -= count
            goods.save()
            total_money += goods.goods_oprice * count
            print("totalmone",total_money)
        else:
            carts_list = data.getlist("car_id")
            car_list = Carts.objects.filter(user_id=user_id, id__in=carts_list)
            if not car_list.exists():
                return HttpResponse("请选择商品！")

            # 判断库存是否充足
            for car in car_list:
                print(car.goods_id, car.count)
                goods = Goods.objects.filter(id=car.goods_id, status=1).first()

user/templates/user_common/cart.html
{% extends 'base/user_base.html' %}
{% load static %}
{% load manager_extras %}

{% block title %}
    <title>天天生鲜-购物车</title>
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
    {% include 'base/user_header.html' %}
    <div class="total_count">全部商品<em>{{ carts_list.count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品现价</li>
		<li class="col03">商品原价</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="{% url 'user:place_order' %}" method="post">
    {% csrf_token %}
    {% for carts in carts_list %}
    <ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="carts_name" checked value="{{ carts.id }}"></li>
		<li class="col02"><img src="/static/{{ carts.goods.goods_pic }}"></li>
		<li class="col03">{{ carts.goods.goods_name|set_goods_name}}</li>
		<li class="col04" id="oprice_{{ carts.id }}">{{ carts.goods.goods_oprice }}元</li>
		<li class="col05"><del>{{ carts.goods.goods_xprice }}</del>元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl" id="add_{{ carts.id }}" onclick="change_count('add',{{ carts.id }})">+</a>
				<input type="text" class="num_show fl" value="{{ carts.count }}" id="carts_{{ carts.id }}" onblur="show_value({{ carts.id }})">
				<a href="javascript:;" class="minus fl" id="red_{{ carts.id }}" onclick="change_count('delete',{{ carts.id }})">-</a>
			</div>
		</li>
		<li class="col07"><span id="xj_{{ carts.id }}">{% widthratio carts.goods.goods_oprice 1 carts.count%}</span>元</li>
		<li class="col08"><a onclick="del({{ carts.id }})" href="javascript:">删除</a></li>
	</ul>
    {% endfor %}

	<ul class="settlements">
		<li class="col01"><button  onclick="check_all('on')" type="button">全选</button></li>
		<li class="col02"><button onclick="check_all('out')" type="button">全不选</button></li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="total">42.60</em><br>共计<b id="total_number">{{carts_list.count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
{% endblock %}

{% block script %}
    <script>
    //删除某条购物车
    function del(id){
        var csrftoken  = $("input[name='csrfmiddlewaretoken']").val();
        $.ajax({
        url:"{% url 'user:carts' %}",
        type:"post",
        dataType:"json",
        data:{"carts_id":id,"csrfmiddlewaretoken":csrftoken,'type':'delete'},
        success:function (data) {
            window.location.href = '/user/carts'
            }
        })
    }
    //计算总价钱
    function total() {
        var input = $("input[class='num_show fl']");
        console.log(input);
        var total=0;
        $("span[id*='xj_']").each(function (obj,ev) {
            var len = $(this).parent().prevAll($('.col01')).children('form input[type=checkbox]:checked').length;
            console.log(len);
            if(len==1){
                var xj=$(this).html();
                console.log(xj);
                total+=Number(xj);
                console.log(total)
            }
        });
        $('#total').html(total)
    }
    total();
    //全选和反选
    function check_all(type) {
        if(type=='on'){
             $('form input[type=checkbox]').prop('checked',true);
        }else {
             $('form input[type=checkbox]').prop('checked',false);
        }
        total();
        set_number();
    }
    //计算选中商品的数量
    function set_number(){
        var total_number = $('form input[type=checkbox]:checked').length;
        $('#total_number').html(total_number);
        total()
    }
    //每次选中或者取消都修改状态
    $("form input[type=checkbox]").click(function () {
        set_number()
    });

    //修改数量
    change_count = function (type,carts_id) {
            var count = parseInt($('#carts_'+carts_id).val());
            console.log(count);
            if(count<=0){
                $('#show_count').val(1)
            }
            else {
                if(type=="add"){
                count+=1;
                }else{
                    if(type=="delete"){
                         if(count>1){count-=1}
                    }
                }
                console.log('count',count);
                show_number(count,carts_id)
            }
        };
    function show_value(carts_id) {
        var count = $('#carts_'+carts_id).val();
        show_number(count,carts_id)
    }
    function show_number(count,carts_id) {
            var csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]').val();
            var price = parseInt($("#oprice_"+carts_id).text());
            console.log(price,2222222);
            $.ajax({
                url:"{% url 'user:carts_check_count' %}",
                data:{carts_id:carts_id,csrfmiddlewaretoken:csrfmiddlewaretoken,count:count},
                dataType:"json",
                type:"post",
                success:function (data) {
                if(data.status == 1){
                    $('#carts_'+carts_id).val(data.data);
                    $('#xj_'+carts_id).text(data.data*price);
                    console.log(data.data*price,1111);
                    total()
                    }
                    else{
                        window.alert("商品已下架，请选择其他商品。");
                        window.location.href = data.data
                        }
                }
            })
        }

    </script>
{% endblock %}

user/templates/user_common/comment.html
{% extends 'base/user_base.html' %}
{% load static %}
{%load manager_extras%}

{% block title %}
    <title>天天生鲜-订单评价</title>
{% endblock %}

{% block style %}
    <script src="{% static "user/js/jquery.js" %}"></script>
    <script src="{% static "user/js/jquery.raty.min.js" %}"></script>

    <style>
    body{width: 1000px;margin:0 auto}

    </style>
{% endblock %}

{% block content %}
    {% include 'base/user_header.html' %}
    <div class="body clearfix">
    <ul class="order_goods_list clearfix">
        <li class="col01">商品图片</li>
        <li class="col02">商品名称</li>
        <li class="col03">商品数量</li>
        <li class="col04">商品单价</li>
        <li class="col03">商品总价</li>
        <li class="col01"><img src="/static/{{ o.goods.goods_pic }}"></li>
        <li class="col02"><a href="{% url 'goods:goods'%}?goods_id={{ o.goods.id }}">{{ o.goods.goods_name | set_goods_name }}</a></li>
        <li class="col03">{{ o.number }}</li>
        <li class="col04">{{ o.money }}元</li>
        <li class="col03"><em>{% widthratio o.money 1 o.number %}</em></li>
    </ul>
    </div>
    <form method="post" action="{% url 'user:comment' o.id%}">
    	{% csrf_token %}
    <input type="hidden" name="orderinfo_id" value="{{ o.id }}">
    <div class="clearfix">
        <div class="fl">商品评分：</div>
        <div id="star1" class="fl"></div>
    </div>
    <div class="clearfix">
        <div class="fl">客服评分：</div>
        <div id="star2" class="fl"></div>
    </div>
    <div class="clearfix">
        <div style="float: left">物流评分：</div>
        <div id="star3" class="fl"></div>
    </div>
    <div>
        <textarea name="content" id="order"></textarea>
    </div>
    <div>
        <input type="checkbox" name="is_anonymous" value="1">匿名评价
    </div>
    <script type="text/javascript">
		$('#star1').raty({
            path: '/static/user/img/',
            scoreName: "goods_score",
        });
		$('#star2').raty({
            path: '/static/user/img/',
            scoreName: "service_score",
        });
		$('#star3').raty({
            path: '/static/user/img/',
            scoreName: "logistics_score",
        });
	</script>
    <div>
        <button>提交评论</button>
    </div>

    </form>
{% endblock %}



{% block script %}
    <script src="/static/ckeditor/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("order",{uiColor:'#5dd733'})
    </script>
{% endblock %}

user/templates/user_common/user_center_order.html
{% extends 'base/user_base.html' %}
{% load static %}
{% load manager_extras %}

{% block title %}
    <title>天天生鲜-用户中心</title>
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
    {% include 'base/user_header.html' %}
    <div class="main_con clearfix">
		{% include 'base/user_center.html' %}
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
            {% for order in order_list %}
                <ul class="order_list_th w978 clearfix">
                        <li class="col01">{{ order.add_time }}</li>
                        <li class="col02">订单号：{{ order.total_code }}</li>
                        <li class="col02 stress">{% if order.pay_status %}已支付{% else %}未支付{% endif %}</li>
                </ul>
                <table class="order_list_table w980">
                    <tbody>
                        <tr>
                            <td width="55%">
                                {% for o in order.order_info_set.all %}
                                 <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="/static/{{ o.goods.goods_pic }}"></li>
                                    <li class="col02">{{ o.goods.goods_name | set_goods_name }}<em>{% widthratio o.money 1 o.number %}</em></li>
                                    <li class="col03">{{ o.number }}</li>
                                    <li class="col04">{{ o.money }}元</li>
                                    <li class="col03">
                                    {% if  o.order.pay_status %}
                                        {% if o.send_status%}
                                            {% if o.receive_status %}
                                                {% if o.comment_status %}
                                                    <a href="">查看评价</a>
                                                    {% else %}
                                                    <a href="{% url 'user:comment' o.id%}">点击评价</a>
                                                {% endif %}
                                                {% else %}
                                                <a href="{% url 'user:receive_goods' o.id%}">点击收货</a>
                                            {% endif %}
                                            {% else %}
                                            <input type="button" value="催单" onclick="f()">
                                            <script>
                                            function f() {
                                                $.ajax({
                                                    url:"{% url 'user:reminder' o.id%}",
                                                    type:"get",
                                                    success:function (data) {
                                                        if(data.status==1){
                                                            window.alert("催单成功")
                                                        }
                                                        else{
                                                            if(data.status==2){}
                                                        }
                                                    },
                                                    error:function () {
                                                        window.alert("服务器有误！")
                                                    }
                                                })
                                            }
                                            </script>
                                        {% endif %}
                                        {% else %}
                                        <a href="{% url 'user:pay_order' order.id%}">去付款</a>
                                    {% endif %}
                                    </li>
                                </ul>
                                {% endfor %}
                            </td>
                            <td width="15%">{{ order.total_money }}元</td>
                        {% if order.pay_status %}
                            <td width="15%">已支付</td>
                            <td width="15%">{{ order.pay_time }}</td>
                        {% else %}
                            <td width="15%">待付款</td>
                            <td width="15%"><a href="{% url 'user:pay_order' order.id%}" class="oper_btn">去付款</a></td>
                        {% endif %}
                            </tr>
                        </tbody>
                    </table>
                {% empty %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">暂无订单</li>
                </ul>
            {% endfor %}
            <div class="pagenation">
            {% if order_list.has_previous %}
                <a href="{% url 'user:user_order' %}?page={{ order_list.previous_page_number }}">&lt;上一页</a>
            {% endif %}
            {% for page in page_list %}
                {% if request.GET.page %}
                    {% if page == request.GET.page|add:0 %}
                        <a href="{% url 'user:user_order' %}?page={{ page }}" class="active">{{ page }}</a>
                    {% elif  request.GET.page|add:0 > order_list.number and page == 1%}
                        <a href="{% url 'user:user_order' %}?page={{ page }}" class="active">{{ page }}</a>
                    {% else %}
                        <a href="{% url 'user:user_order' %}?page={{ page }}">{{ page }}</a>
                    {% endif %}
                {% else %}
                     {% if page == 1 %}
                        <a href="{% url 'user:user_order' %}?page={{ page }}" class="active">{{ page }}</a>
                        {% else %}
                        <a href="{% url 'user:user_order' %}?page={{ page }}">{{ page }}</a>
                     {% endif %}
                {% endif %}
            {% endfor %}
             {% if order_list.has_next %}
                <a href="{% url 'user:user_order' %}?page={{ order_list.next_page_number }}">下一页></a>
             {% endif %}
            </div>
		</div>
	</div>
{% endblock %}

{% block script %}
{% endblock %}