QSHOP/urls.py
from django.contrib import admin
from django.urls import path,include

from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('goods/',include('goods.urls',namespace='goods')),
    path('manager/',include('manager.urls',namespace='manager')),
    path('user/',include('user.urls',namespace='user')),
    #用于重定向
    path('',RedirectView.as_view(url="/goods/index")),

]

manager/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('check_username/',views.check_username,name='check_username'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('add_goods/',views.add_goods,name='add_goods'),
    path('goods_list/',views.goods_list,name='goods_list'),
    path('goods_detail/<int:id>',views.goods_detail,name='goods_detail'),
    path('update_status/<int:id>',views.update_status,name='update_status'),
    path('manager_message/',views.manager_message,name='manager_message'),
    path('forget_password/',views.forget_password,name='forget_password'),
    path('send_message/',views.send_message,name='send_message'),
    path('update_goods/<int:id>',views.update_goods,name='update_goods'),
    path('update_message/',views.update_message,name='update_message'),
    path('order_list/',views.order_list,name='order_list'),
    path('send_goods/<int:orderinfo_id>',views.send_goods,name='send_goods'),
    path('order_detail/<int:orderinfo_id>',views.order_detail,name='order_detail'),
]
app_name='manager'

user/urls.py
from django.urls import path,re_path
from user import views

from django.views.decorators.csrf import csrf_exempt
from QSHOP.common import user_login_valid
urlpatterns = [
    path('register/',views.Register.as_view(),name='register'),
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('carts/',views.carts.as_view(),name ="carts"),
    path('user_info/',views.User_info.as_view(),name ="user_info"),
    path('user_order/',views.User_order.as_view(),name ="user_order"),
    path('user_site/',views.User_site.as_view(),name ="user_site"),
    path('set_address/',views.set_address,name ="set_address"),
    path('carts_check_count/',views.carts_check_count,name ="carts_check_count"),
    path('place_order/',views.place_order,name ="place_order"),
    path('create_order/',views.create_order,name ="create_order"),
    path('select_carts_count/',views.select_carts_count,name ="select_carts_count"),
    path('pay_order/<int:order_id>',views.pay_order,name ="pay_order"),
    path('test_time/',views.test_time,name ="test_time"),
    path('return_url/',views.return_url,name ="return_url"),
    path('receive_goods/<int:orderinfo_id>',views.receive_goods,name ="receive_goods"),
    path('comment/<int:orderinfo_id>',views.comment,name ="comment"),
    path('reminder/<int:orderinfo_id>',views.reminder,name ="reminder"),

]
app_name='user'

urlpatterns += [
    # 使用装饰器装饰类
    path('Demo/', user_login_valid(views.Demo.as_view()), name="Demo"),
    # re_path('demo/(\d+)/(?P<id2>\d+)',views.demo,name='demo'),
]

user/models.py
from django.db import models
from goods.models import Goods
from manager.models import Manager



#卖家用户表
class User(models.Model):
    class Meta:
        verbose_name = "买家用户"
        verbose_name_plural = "买家用户"

    user_name = models.CharField(max_length=20)
    email = models.EmailField('买家邮箱')
    password = models.CharField(max_length=32,verbose_name='买家密码')
    image = models.ImageField(upload_to='media/user/image',default='media/user/image/user_default.jpg')
    is_login = models.BooleanField(default=0)

    def __str__(self):
        return self.user_name


#购物车表
class Carts(models.Model):
    class Meta:
        verbose_name = "购物车"
        verbose_name_plural = "购物车"
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='买家')
    goods = models.ForeignKey(Goods,on_delete=models.CASCADE,verbose_name="商品")
    count = models.IntegerField('数量')


#收货地址表
class Address(models.Model):
    class Meta:
        verbose_name = "收获地址"
        verbose_name_plural = "收获地址"
    username = models.CharField(max_length=25,verbose_name="收货人姓名")
    userphone = models.CharField(max_length=20,verbose_name="收货人电话")
    address = models.CharField(max_length=255, verbose_name="详细地址")
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="买家")
    isdefault = models.BooleanField(default=0,verbose_name="是否默认地址")        #0否，1是
    createtime = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")


#订单总表
class Order(models.Model):
    class Meta:
        verbose_name = "订单"
        verbose_name_plural = "订单"
    total_code = models.CharField(max_length=17,unique=True,verbose_name="订单总编号")
    user = models.ForeignKey(User,verbose_name="买家",on_delete=models.DO_NOTHING)
    add_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")
    contacts = models.CharField(max_length=30, verbose_name="收货人")
    address = models.CharField(max_length=255,verbose_name="收货地址")
    phone = models.CharField(max_length=20,verbose_name="收货人电话")
    pay_status = models.BooleanField(default=0,verbose_name="支付状态")  #默认为0，未支付
    pay_time = models.DateTimeField(null=True,verbose_name="支付时间")
    total_money = models.FloatField(verbose_name="价格")
    def __str__(self):
        return self.total_code


#订单详情表
class Order_info(models.Model):
    class Meta:
        verbose_name = "订单详情"
        verbose_name_plural = "订单详情"
    order_code = models.CharField(max_length=32,verbose_name="订单详细编号")
    order = models.ForeignKey(Order,verbose_name="订单", on_delete=models.DO_NOTHING)
    goods = models.ForeignKey(Goods,verbose_name="商品", on_delete=models.DO_NOTHING)
    number = models.IntegerField(default=1, verbose_name="数量")
    money = models.FloatField(verbose_name="价格")
    send_status = models.BooleanField(default=0,verbose_name="发货状态")
    send_time = models.DateTimeField(null=True,verbose_name="发货时间")
    receive_status = models.BooleanField(default=0, verbose_name="收货状态")
    receive_time = models.DateTimeField(null=True, verbose_name="收货时间")
    comment_status = models.BooleanField(default=0, verbose_name="评价状态")
    manager = models.ForeignKey(Manager, verbose_name="商家", on_delete=models.DO_NOTHING)


#用户爱好表
class Hobby(models.Model):
    class Meta:
        verbose_name = "买家爱好"
        verbose_name_plural = "买家爱好"
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='买家')
    goods = models.ForeignKey(Goods,on_delete=models.CASCADE,verbose_name="商品")


#用户评价表
class Comment(models.Model):
    class Meta:
        verbose_name = "商品评价"
        verbose_name_plural = "商品评价"
    goods_score = models.FloatField(verbose_name="商品评分")
    service_score = models.FloatField(verbose_name="客服评分")
    logistics_score = models.FloatField(verbose_name="物流评分")
    content = models.TextField(verbose_name="评价内容")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="评价时间")
    shop_reply = models.TextField(verbose_name="商家回复")
    reply_time = models.DateTimeField(null=True, verbose_name="商家回复时间")
    user = models.ForeignKey(User,verbose_name="买家用户",on_delete=models.CASCADE)
    orderinfo = models.ForeignKey(Order_info,on_delete=models.CASCADE,verbose_name="订单详情")
    is_anonymous = models.BooleanField(verbose_name="是否匿名评价")

manager/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from QSHOP.common import set_password,login_valid,send_manager_email,set_page
from .models import Manager
from goods.models import Type,Goods
import json
from django.http import JsonResponse
import random
from user.models import Order,Order_info
from django.utils import timezone

@login_valid
def index(request):
    return render(request,'common/index.html')


#注册
def register(request):
    error = ''
    if request.method == 'POST':
        data = request.POST
        username = data.get('username')
        email = data.get('email')
        password1 = data.get('password1')
        password2 = data.get('password2')
        print(username,email,password1,password2)
        if password1 != password2:
            error =  '两次密码不一致！'
            return render(request, 'common/register.html', {"error": error})
        md5_pwd = set_password(set_password(password1))
        #对用户名需要加校验：看当前的用户名是否已经注册
        m = Manager.objects.filter(manager_name=username)
        if not m.exists():
            m = Manager.objects.create(manager_name=username,email=email,password=md5_pwd)
            return HttpResponseRedirect('/manager/login')
        error = '用户名重复'
    return render(request,'common/register.html',{"error":error})


#检测用户名是否重复
def check_username(request):
    result = {'flag':0 }
    data = request.GET
    username = data.get('username')
    if username != '':
        m = Manager.objects.filter(manager_name = username)
        if not m.exists():
            result['flag'] = 1   #0代表用户名重复，1代表用户名无重复
    #返回json对象的两种方式：
    #第一种：通过json.dumps()进行转化
    # return HttpResponse(json.dumps(result))
    #第二种：通过JsonResponse返回。
    return JsonResponse(result)


#登录
def login(request):
    error = ''
    if request.method == 'POST':
        data = request.POST
        manager_name = data.get('username')
        password = data.get('password')
        print(manager_name,password)
        md5_pwd =set_password(set_password(password))
        print(md5_pwd)
        try:
            m = Manager.objects.get(manager_name=manager_name,password=md5_pwd)
            #设置session  设置给request
            request.session['manager_name'] = manager_name
            request.session['id'] = m.id
            #设置cookie  设置给response
            response = HttpResponseRedirect('/manager/index')
            response.set_cookie('manager',manager_name)
            return response
        except:
            error = '用户名或者密码有误！'
    return render(request,'common/login.html',{'error':error})


#退出
def logout(request):
    response = HttpResponseRedirect('/manager/login')
    try:
        del request.session['id']               #删除商家session
        del request.session['manager_name']     #删除买家session
        response.delete_cookie('manager')       # 删除cookie
    except:
        pass
    return response


@login_valid
def add_goods(request):
    if request.method == "POST":
        data = request.POST
        # 接收数据通过在前端定义的name属性接收，接收不到时值为None
        goods_name = data.get('goods_name')
        goods_oprice = data.get('goods_oprice')
        goods_xprice = data.get('goods_xprice')
        goods_count = data.get('goods_count')
        goods_production = data.get('goods_production')
        safe_date = data.get('safe_date')
        goods_method = data.get('goods_method')
        goods_description = data.get('goods_description')
        # 文件类型数据的获取方式
        goods_pic = request.FILES.get('goods_pic')
        goods_address = data.get('goods_address')
        goods_info = data.get('goods_info')
        manager_id = request.session.get('id')
        type = data.get('type')
        status = data.get('status')
        Goods.objects.create(  # 添加进数据库
            goods_name=goods_name,
            goods_oprice=goods_oprice,
            goods_xprice=goods_xprice,
            goods_count=goods_count,
            goods_production=goods_production,
            safe_date=safe_date,
            goods_method=goods_method,
            goods_description=goods_description,
            # 文件类型数据的获取方式
            goods_pic=goods_pic,
            goods_address=goods_address,
            goods_info=goods_info,
            # manager_id = manager_id,
            manager=Manager.objects.get(id=manager_id),
            type_id=type,
            status=status,
        )
        return HttpResponse('商品添加成功！')
    type_list = Type.objects.all()
    return render(request, 'common/add_goods.html', {'type_list': type_list})


@login_valid
def goods_list(request):
    manager_id = request.session.get('id')
    goods_list = Goods.objects.filter(manager_id=manager_id).order_by('-status')
    page = request.GET.get("page", 1)
    data, page_list = set_page(goods_list, 50, page)
    return render(request,'common/goods_list.html',{'goods_list':data,"page_list":page_list})


@login_valid
def goods_detail(request,id):
    manager_id = request.session.get('id')
    goods = Goods.objects.filter(id=id,manager_id=manager_id)
    if goods.exists():
        goods = goods[0]
        return render(request,'common/goods_detail.html',{'goods':goods})
    return render(request,'common/404.html')


@login_valid
def update_status(request,id):
    manager_id =request.session.get('id')
    goods  = Goods.objects.filter(id=id,manager_id=manager_id)
    if goods.exists():
        goods = goods[0]
        if goods.status == 1:
            goods.status = 0
        else:
            if goods.goods_count>0:
                goods.status = 1
        goods.save()     #保存数据
        return HttpResponseRedirect('/manager/goods_list')
    return render(request,'common/404.html')


@login_valid
def manager_message(request):
    manager_id = request.session.get('id')
    message = ""
    if request.method == "POST":
        o_pwd = request.POST.get('original_password')
        c_pwd = request.POST.get('current_password')
        o_md5 = set_password(set_password(o_pwd))
        m = Manager.objects.filter(id=manager_id,password=o_md5)
        if m.exists():
            c_md5 = set_password(set_password(c_pwd))
            # m.update(password=c_md5)
            c = m[0]
            c.password = c_md5
            c.save()
            return redirect('manager:login')
        message = "密码修改失败，原密码输入有误！"
    manager = Manager.objects.filter(id=manager_id)
    return render(request,'common/manager_message.html',{'manager':manager[0],'message':message})


@login_valid
def update_message(request):
    manager_id = request.session.get('id')
    manager = Manager.objects.filter(id=manager_id)
    if request.method == "POST":
        m = manager[0]
        data = request.POST
        manager_name = data.get('manager_name')
        email = data.get('email')
        image = request.FILES.get('image')
        m.manager_name = manager_name
        m.email = email
        if image:
            m.image = image
        m.save()
        return redirect('manager:manager_message')
    return render(request,'common/update_message.html',{'manager':manager[0]})


@login_valid
def update_goods(request,id):
    manager_id = request.session.get('id')
    if request.method == "POST":
        data = request.POST
        goods_id = data.get('goods_id')
        goods_name = data.get('goods_name')
        goods_oprice = data.get('goods_oprice')
        goods_xprice = data.get('goods_xprice')
        goods_count = data.get('goods_count')
        safe_date = data.get('safe_date')
        goods_method = data.get('goods_method')
        goods_description = data.get('goods_description')
        # 文件类型数据的获取方式
        goods_pic = request.FILES.get('goods_pic')
        goods_address = data.get('goods_address')
        goods_info = data.get('goods_info')
        type = data.get('type')
        status = data.get('status')
        manager_id = request.session.get('id')
        goods = Goods.objects.get(manager_id=manager_id,id=goods_id)
        goods.goods_name = goods_name
        goods.goods_oprice = goods_oprice
        goods.goods_xprice = goods_xprice
        goods.goods_count = goods_count
        goods.safe_date = safe_date
        goods.goods_method = goods_method
        goods.goods_description = goods_description
        # 文件类型数据的获取方式
        if goods_pic:
            goods.goods_pic = goods_pic
        goods.goods_address = goods_address
        goods.goods_info = goods_info
        goods.type_id = type
        goods.status = status
        goods.save()
        return redirect('manager:goods_detail',goods_id)
    type_list = Type.objects.all()
    goods = Goods.objects.filter(id=id,manager_id=manager_id)
    if goods.exists():
        return render(request,'common/update_goods.html',{'goods':goods[0],'type_list':type_list})
    return render(request,'common/404.html')


#重置密码
def forget_password(request):
    message = ''
    if request.method == "POST":
        data = request.POST
        email = data.get('email')
        password = data.get('password')
        code = data.get('code')
        if code and email == request.session.get('email') and code.lower() == request.session.get('code'):
            md5_pwd = set_password(set_password(password))
            m = Manager.objects.filter(email=email).update(password=md5_pwd)
            del request.session['email']
            del request.session['code']
            return HttpResponseRedirect('/manager/login')
        message = "验证码或者邮箱有误！"
    return render(request, 'common/forget_password.html',{'message':message})


#发送验证码
def send_message(request):
    email = request.GET.get('email')
    m = Manager.objects.filter(email=email)
    res = {'flag':0,'data':'请输入正确的邮箱地址！'}
    if m.exists():
        candidate_string = 'ABC1D2EF3GH4IJ5KL6MN70PQ8RS9TUV0WXYZ'  # 候选字符串
        message = ''
        # 生成验证码
        for i in range(0, 5):
            one_str = candidate_string[random.randint(0, len(candidate_string) - 1)]
            message += one_str
        request.session['email'] = email

manager/templates/common/forget_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>重置密码</title>

  <!-- Custom fonts for this template-->
  <link href="/static/manager/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="/static/manager/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-2">忘记密码?</h1>
                    <p class="mb-4">请输入邮箱，稍后会发送验证码重置密码！</p>
                  </div>
                  <form class="user" method="post">
                      {% csrf_token %}
                    <div class="form-inline" style="margin-bottom: 16px">
                      <input type="email" name="email" class="form-control form-control-user" id="email" aria-describedby="emailHelp" placeholder="请输入邮箱地址">
{#                        <input class="btn btn-default" type="button" id="code" onclick="f()">#}
                       <button class="btn btn-primary" type="button"  onclick="f()">发送验证码</button>
                    <div><span style="color: red;padding-left: 14px" id="message"></span></div>
                    </div>

                    <div class="form-group" width="250px">
                    <input  type="password"  name="password" class="form-control form-control-user" id="password" aria-describedby="emailHelp" placeholder="密码">
                    </div>
                    <div class="form-group">
                    <input type="text" class="form-control form-control-user" name="code" id="verify_Code" aria-describedby="emailHelp" placeholder="验证码">
                    </div>
                    <div style="color: red;margin-left: 10px">{{ message }}</div>
                    <input type="submit" class="btn btn-primary btn-user btn-block" value="重置密码">
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'manager:register' %}">创建账号!</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'manager:login' %}">已有账号去登录！</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="/static/manager/vendor/jquery/jquery.min.js"></script>
  <script src="/static/manager/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/manager/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="/static/manager/js/sb-admin-2.min.js"></script>
  <script>
      function f() {
          email = $('#email').val();
          console.log(email);
          if(email==""){
              {#window.alert("请输入邮箱！");#}
              $('#message').text("请输入合法邮箱");
              $('#email').focus();     //自动聚焦到邮箱输入框
          }else{
               $.ajax({
                  url:"{% url 'manager:send_message' %}",
                  type:'get',
                  dataType:'json',
                  data:{email:email},
                  success:function (data) {
                      if(data.flag==1){$('#message').css('color','green')}
                      else{
                          $('#message').css('color','red');
                          $('#email').focus();     //自动聚焦到邮箱输入框
                      }
                      $('#message').text(data.data);
              }
           })
          }
      }
  </script>

</body>

</html>

manager/templates/common/goods_list.html
{% extends 'base/manage_base.html' %}
{% load static %}
{% load manager_extras %}

{% block title %}
    <title>商品列表</title>
{% endblock %}

{% block style %}

  <link href="/static/manager/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    <style>
    th{color: black;}
    tr{text-align: center}
    </style>
{% endblock %}

{% block content %}
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Tables</h1>
          <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">商品列表</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                      <th width="160px">商品名称</th>
                      <th>现价</th>
                      <th>原价</th>
                      <th>商品数量</th>
                      <th>生产日期</th>
                      <th>保质期</th>
                      <th width="120px">操作</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for goods in goods_list %}
                    <tr>
                      <td><a href="{% url 'manager:goods_detail' goods.id %}">{{ goods.goods_name | set_goods_name }}</a></td>
                      <td>{{ goods.goods_oprice }}</td>
                      <td>{{ goods.goods_xprice }}</td>
                      <td>{{ goods.goods_count }}</td>
                      <td>{{ goods.goods_production }}</td>
                      <td>{{ goods.safe_date }}</td>
                      <td>
                          {% if goods.status == 1 %}
                           <a href="{% url 'manager:update_status' goods.id %}" class="btn btn-warning btn-sm" style="float: left">下架</a>
                          {% else %}
                          <a href="{% url 'manager:update_status' goods.id %}" class="btn btn-primary btn-sm"  style="float: left">上架</a>
                          {% endif %}
                          <a href="{% url 'manager:update_goods' goods.id %}" class="btn btn-success btn-sm"  style="float: left">编辑</a>
                      </td>
                    </tr>
{#                      {% empty %}#}
{#                      <tr>#}
{#                      <td colspan="7">当前没有商品，请添加商品。</td>#}
{#                      </tr>#}
                  {% endfor %}
                  </tbody>
                </table>
                <ul class="list">
               {% if goods_list.has_previous %}
                <a href="{% url 'manager:goods_list' %}?page={{ goods_list.previous_page_number }}" class="btn-sm btn">&lt;</a>
            {% endif %}
            {% for page in page_list %}
                {% if request.GET.page %}
                    {% if page == request.GET.page|add:0 %}
                        <a href="{% url 'manager:goods_list' %}?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                    {% elif  request.GET.page|add:0 > goods_list.number and page == 1%}
                        <a href="{% url 'manager:goods_list' %}?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                    {% else %}
                        <a href="{% url 'manager:goods_list' %}?page={{ page }}" class="btn-sm btn">{{ page }}</a>
                    {% endif %}
                {% else %}
                     {% if page == 1 %}
                        <a href="{% url 'manager:goods_list' %}?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                        {% else %}
                        <a href="{% url 'manager:goods_list' %}?page={{ page }}" class="btn-sm btn">{{ page }}</a>
                     {% endif %}
                {% endif %}
            {% endfor %}
             {% if goods_list.has_next %}
                <a href="{% url 'manager:goods_list' %}?page={{ goods_list.next_page_number }}" class="btn-sm btn">&gt;</a>
             {% endif %}
            </ul>

              </div>
            </div>
          </div>

{% endblock %}

{% block script %}
<!-- Page level plugins -->
  <script src="/static/manager/vendor/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/manager/vendor/datatables/dataTables.bootstrap4.min.js"></script>

  <!-- Page level custom scripts -->

    <!--
     <script src="/static/manager/js/demo/datatables-demo.js"></script>
    -->
{% endblock %}

manager/templates/common/manager_message.html
{% extends 'base/manage_base.html' %}
{% load static %}
{% load manager_extras %}

{% block title %}
    <title>个人信息</title>
{% endblock %}

{% block style %}
    <style>
    tr{color: black;}
    img{width: 150px;height: 150px;}
    </style>
{% endblock %}

{% block content %}
<div style="padding-bottom: 10px">
    <a href="{% url 'manager:index' %}" class="btn btn-success">返回首页</a>
    <a href="{% url 'manager:update_message' %}" class="btn btn-primary">编辑信息</a>
    <a class="btn btn-primary" href="{% url 'manager:logout' %}" data-toggle="modal" data-target="#changepwd">修改密码</a>
</div>
<table class="table table-bordered table-hover">
    <tr>
        <td rowspan="4"><img src="/static/{{ manager.image }}" alt="{{ manager.manager_name }}"></td>
        <td>用户名：{{ manager.manager_name }}</td>
    </tr>
    <tr>
        <td>密&nbsp;&nbsp;码：{{ manager.password | set_password}}</td>
    </tr>
    <tr>
        <td>邮&nbsp;&nbsp;箱：{{ manager.email }}</td>
    </tr>
    <div style="color: red">{{ message }}</div>
     <div class="modal fade" id="changepwd" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">确定修改密码?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
          <form action="{% url 'manager:manager_message' %}" method="post">
              {% csrf_token %}
            <input class="modal-body" placeholder="请输入原密码" name="original_password" type="password" required>
            <input class="modal-body" placeholder="请输入现密码" name="current_password" type="password" required>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">关闭</button>
              <button class="btn btn-primary" type="submit">提交</button>
            </div>
        </form>
    </div>
  </div>

</table>

{% endblock %}


{% block script %}


{% endblock %}

manager/templates/common/update_message.html
{% extends 'base/manage_base.html' %}
{% load static %}

{% block title %}
    <title>天天生鲜--个人信息修改</title>
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
    <form action="{% url 'manager:update_message'%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
         <input type="text" class="form-control" placeholder="请输入昵称" value="{{ manager.manager_name }}" required  name="manager_name" maxlength="50">
    </p>
    <p>
         <input type="email" class="form-control" placeholder="请输入邮箱" value="{{ manager.email }}" required  name="email">
    </p>
    <p>
        <img src="/static/{{ manager.image }}" alt="">
         <input type="file" class="form-control" placeholder="商品简介"   name="image" >
    </p>

    <button class="btn btn-primary">提交</button>
    </form>
{% endblock %}

{% block script %}
{% endblock %}